---
- hosts: all

  become: true
  tasks:
    - name: update docker container with WatchTower
      ansible.builtin.shell: |
        docker run --rm \
        --name WatchTower \
        -v /var/run/docker.sock:/var/run/docker.sock \
        containrrr/watchtower \
        --run-once \
        --cleanup \
        --include-restarting \
        --rolling-restart \
        --include-stopped